### ISSUE TITLE
Don't Print a Table Every Time

### ISSUE THREAD

**Issue by maxnz** [StoDevX/stograde#187]
The advantages of not printing the table every time is that the toolkit won't be required to check every assignment every time, and thus wouldn't be required to load all of those specs every time. The speedup from not loading every spec would be helpful, especially because in #186 the JSON caching is removed (for simplicity).

One way to achieve this is to use a `--table` flag to trigger the printout.
Another idea is to use subcommands such as `record`, `ci`, `table` instead of the `--record`, `--ci` and `--table` flags.

**Comment by maxnz** [comment]
Personally I like the idea of splitting out the functionality into the subcommands. We could even add another subcommand `web` that then takes one assignment and triggers the web CLI.

**Comment by hawkrives** [comment]
That sounds good to me.
