### ISSUE TITLE
travis+docker: Push `latest` tag as well

### ISSUE THREAD

**Issue by rye** [StoDevX/stograde#57]
Currently, we're pushing `HEAD` and tags, and that's cool, but we should build and push `latest` on every new tag.

The hard part of this is doing version comparison. Since the scripts are in Ruby, we can just use `Gem::Version` to compare the tag with all of the previous ones, but that's pretty meh.

**Comment by maxnz** [comment]
Based on the presence of [these lines](https://github.com/StoDevX/stograde/blob/master/.travis.yml#L50-L54) in the travis config, I believe this was completed.
