### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/stograde#80]
Now that we actually have CS241 support (#73), it may be time to rename this thing.

My ideas:

- `cskit`
- `stocstk`
- … _maybe_ `cstk`? I don't like this one as much... 
- @maxnz `stograde` (I like this one)
- @maxnz `csgtk`

@rye, @maxnz, @drewvolz thoughts?

**Comment by maxnz** [comment]
Maybe `stograde` or `csgtk` (for cs grading toolkit)?

**Comment by drewvolz** [comment]
stograde has a nice ring to it.

**Comment by rye** [comment]
I like `sto` `cs` and any subset of the word `grade` as stems. So perhaps `stograde` or `csgkit` or something like that.

**Comment by hawkrives** [comment]
I like `stograde`. 

I'll probably start the renaming process tomorrow?

**Comment by maxnz** [comment]
I think we can close this now
